### ISSUE TITLE
Broken in latest dokuwiki

### ISSUE THREAD

**Issue by nightuser** [foundata/dokuwiki-template-monobook#3]
Less error: "parse error: failed at `#line-height: 1em;` allext/monobook/static/css/screen.css on line 436"

**Comment by andreashaerter** [comment]
Fixed with f2266fda5ac479685942dfba79a1d4a61fb11ec2. I released a new version of monobook, please install the [latest update](https://www.dokuwiki.org/template:monobook#download).
