### ISSUE TITLE
Disappears in the toolbox sidebar in new template

### ISSUE THREAD

**Issue by serrafa** [foundata/dokuwiki-template-monobook#5]
With the last upgrade I lost the toolbox in the sidebar and asks me to create a wiki: toolbox. What happened?

**Comment by andreashaerter** [comment]
The config parser changed an breaks the template config. The next template version (comes tomorrow) will fix this.

**Comment by andreashaerter** [comment]
New release is out, just get it from https://www.dokuwiki.org/template:monobook - simply uncompress and copy it over your current /lib/tpl/monobook for an upgrade.
